services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=${SPRING_MARIADB_DATABASE}'
      - 'MARIADB_PASSWORD=${SPRING_MARIADB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${SPRING_MARIADB_ROOT_PASSWORD}'
      - 'MARIADB_USER=${SPRING_MARIADB_USER}'
    ports:
      - '3306'